"""empty message

Revision ID: 0240a39c0c49
Revises: 1411634833bb
Create Date: 2025-02-13 09:45:45.192210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0240a39c0c49'
down_revision = '1411634833bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('theme',
    sa.Column('theme_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('theme_name', sa.String(length=100), nullable=False),
    sa.Column('theme_description', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_on', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('updated_on', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('theme_id'),
    sa.UniqueConstraint('theme_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('theme')
    # ### end Alembic commands ###
