"""empty message

Revision ID: 1169a9f4f294
Revises: 54622122b290
Create Date: 2025-02-23 00:50:38.008290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1169a9f4f294'
down_revision = '54622122b290'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_api', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ecreds_name', sa.String(length=100), nullable=False))
        batch_op.create_unique_constraint(None, ['ecreds_name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_api', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('ecreds_name')

    # ### end Alembic commands ###
