"""empty message

Revision ID: 1411634833bb
Revises: 8ae99ec6c453
Create Date: 2025-02-12 16:15:51.489488

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1411634833bb'
down_revision = '8ae99ec6c453'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userv1', schema=None) as batch_op:
        batch_op.alter_column('division',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.drop_index('division')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userv1', schema=None) as batch_op:
        batch_op.create_index('division', ['division'], unique=True)
        batch_op.alter_column('division',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###
