"""empty message

Revision ID: 18224a532314
Revises: e57ec5521145
Create Date: 2025-02-17 10:51:41.445660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18224a532314'
down_revision = 'e57ec5521145'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hrpears',
    sa.Column('hrpears_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hrpears_host', sa.String(length=200), nullable=False),
    sa.Column('hrpears_root', sa.String(length=200), nullable=False),
    sa.Column('hrpears_user', sa.String(length=200), nullable=False),
    sa.Column('hrpears_password', sa.String(length=200), nullable=False),
    sa.Column('hrpears_dbname', sa.String(length=200), nullable=False),
    sa.Column('hrpears_table', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_on', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('updated_on', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('hrpears_id'),
    sa.UniqueConstraint('hrpears_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hrpears')
    # ### end Alembic commands ###
