"""empty message

Revision ID: 1d2070bfafc8
Revises: d592d4ce77db
Create Date: 2025-03-21 13:30:42.339627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d2070bfafc8'
down_revision = 'd592d4ce77db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sys_setting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('system_notice', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sys_setting', schema=None) as batch_op:
        batch_op.drop_column('system_notice')

    # ### end Alembic commands ###
