"""empty message

Revision ID: 1f23504b1e4e
Revises: 3d9e95f5235f
Create Date: 2025-02-11 11:25:12.693289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f23504b1e4e'
down_revision = '3d9e95f5235f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_api',
    sa.Column('login_api_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('login_api_url', sa.String(length=100), nullable=False),
    sa.Column('login_api_token', sa.String(length=200), nullable=False),
    sa.Column('login_api_content_type', sa.String(length=100), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_on', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('updated_on', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('login_api_id'),
    sa.UniqueConstraint('login_api_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('login_api')
    # ### end Alembic commands ###
