"""empty message

Revision ID: 1f5a18a2a599
Revises: c77263bf43e4
Create Date: 2025-02-16 23:56:18.055790

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1f5a18a2a599'
down_revision = 'c77263bf43e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_logs', schema=None) as batch_op:
        batch_op.alter_column('user',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('activity',
               existing_type=mysql.VARCHAR(length=999),
               nullable=True)
        batch_op.alter_column('created_on',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_index('activity')
        batch_op.drop_index('created_on')
        batch_op.drop_index('user')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_logs', schema=None) as batch_op:
        batch_op.create_index('user', ['user'], unique=True)
        batch_op.create_index('created_on', ['created_on'], unique=True)
        batch_op.create_index('activity', ['activity'], unique=True)
        batch_op.alter_column('created_on',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('activity',
               existing_type=mysql.VARCHAR(length=999),
               nullable=False)
        batch_op.alter_column('user',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###
