"""empty message

Revision ID: 3d9e95f5235f
Revises: ea8427440f4b
Create Date: 2025-02-10 22:18:26.869435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d9e95f5235f'
down_revision = 'ea8427440f4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('external',
    sa.Column('external_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_name', sa.String(length=100), nullable=False),
    sa.Column('external_mobile', sa.String(length=100), nullable=False),
    sa.Column('external_email', sa.String(length=100), nullable=False),
    sa.Column('external_description', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_on', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('updated_on', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('external_id'),
    sa.UniqueConstraint('external_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('external')
    # ### end Alembic commands ###
