"""empty message

Revision ID: 428e834f0fd4
Revises: 8a08b3ecc011
Create Date: 2025-02-17 10:57:24.709948

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '428e834f0fd4'
down_revision = '8a08b3ecc011'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_api',
    sa.Column('ecreds_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ecreds_email', sa.String(length=100), nullable=False),
    sa.Column('ecreds_sender', sa.String(length=100), nullable=False),
    sa.Column('ecreds_password', sa.String(length=100), nullable=False),
    sa.Column('ecreds_templates', sa.String(length=999), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_on', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('updated_on', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('ecreds_id'),
    sa.UniqueConstraint('ecreds_id')
    )
    op.create_table('external_contacts',
    sa.Column('external_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_name', sa.String(length=100), nullable=False),
    sa.Column('external_mobile', sa.String(length=100), nullable=False),
    sa.Column('external_email', sa.String(length=100), nullable=False),
    sa.Column('external_description', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_on', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('updated_on', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('external_id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_table('hrpears_api',
    sa.Column('hrpears_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hrpears_host', sa.String(length=200), nullable=False),
    sa.Column('hrpears_root', sa.String(length=200), nullable=False),
    sa.Column('hrpears_user', sa.String(length=200), nullable=False),
    sa.Column('hrpears_password', sa.String(length=200), nullable=False),
    sa.Column('hrpears_dbname', sa.String(length=200), nullable=False),
    sa.Column('hrpears_table', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_on', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('updated_on', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('hrpears_id'),
    sa.UniqueConstraint('hrpears_id')
    )
    op.create_table('itexmo_api',
    sa.Column('itexmo_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('itexmo_name', sa.String(length=200), nullable=False),
    sa.Column('itexmo_url', sa.String(length=200), nullable=False),
    sa.Column('itexmo_email', sa.String(length=200), nullable=False),
    sa.Column('itexmo_password', sa.String(length=200), nullable=False),
    sa.Column('itexmo_apicode', sa.String(length=200), nullable=False),
    sa.Column('itexmo_contenttype', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_on', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('updated_on', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('itexmo_id'),
    sa.UniqueConstraint('itexmo_id')
    )
    with op.batch_alter_table('emails', schema=None) as batch_op:
        batch_op.drop_index('ecreds_id')

    op.drop_table('emails')
    with op.batch_alter_table('external', schema=None) as batch_op:
        batch_op.drop_index('external_id')

    op.drop_table('external')
    with op.batch_alter_table('itexmo', schema=None) as batch_op:
        batch_op.drop_index('itexmo_id')

    op.drop_table('itexmo')
    with op.batch_alter_table('hrpears', schema=None) as batch_op:
        batch_op.drop_index('hrpears_id')

    op.drop_table('hrpears')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hrpears',
    sa.Column('hrpears_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('hrpears_host', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('hrpears_root', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('hrpears_user', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('hrpears_password', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('hrpears_dbname', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('hrpears_table', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('created_by', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('created_on', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('updated_by', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('updated_on', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('hrpears_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('hrpears', schema=None) as batch_op:
        batch_op.create_index('hrpears_id', ['hrpears_id'], unique=True)

    op.create_table('itexmo',
    sa.Column('itexmo_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('itexmo_url', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('itexmo_email', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('itexmo_password', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('itexmo_apicode', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('itexmo_contenttype', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('created_by', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('created_on', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('updated_by', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('updated_on', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('itexmo_name', mysql.VARCHAR(length=200), nullable=False),
    sa.PrimaryKeyConstraint('itexmo_id'),
    mysql_collate='latin1_swedish_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('itexmo', schema=None) as batch_op:
        batch_op.create_index('itexmo_id', ['itexmo_id'], unique=True)

    op.create_table('external',
    sa.Column('external_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('external_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('external_mobile', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('external_email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('external_description', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('created_by', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('created_on', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('updated_by', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('updated_on', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('external_id'),
    mysql_collate='latin1_swedish_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('external', schema=None) as batch_op:
        batch_op.create_index('external_id', ['external_id'], unique=True)

    op.create_table('emails',
    sa.Column('ecreds_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('ecreds_email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('ecreds_sender', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('ecreds_password', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('ecreds_templates', mysql.VARCHAR(length=999), nullable=True),
    sa.Column('created_by', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('created_on', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('updated_by', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('updated_on', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('ecreds_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('emails', schema=None) as batch_op:
        batch_op.create_index('ecreds_id', ['ecreds_id'], unique=True)

    op.drop_table('itexmo_api')
    op.drop_table('hrpears_api')
    op.drop_table('external_contacts')
    op.drop_table('email_api')
    # ### end Alembic commands ###
