"""empty message

Revision ID: 4492e0fb8958
Revises: 9b9f900c0790
Create Date: 2025-02-24 09:44:27.053010

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4492e0fb8958'
down_revision = '9b9f900c0790'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sys_setting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sys_name', sa.String(length=200), nullable=False))
        batch_op.alter_column('sys_app_name',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
        batch_op.create_unique_constraint(None, ['sys_name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sys_setting', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('sys_app_name',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
        batch_op.drop_column('sys_name')

    # ### end Alembic commands ###
