"""empty message

Revision ID: 4ff49caf100d
Revises: 5e0848a4e8d9
Create Date: 2025-04-07 23:24:14.204325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ff49caf100d'
down_revision = '5e0848a4e8d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userv1', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_email', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('user_section', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userv1', schema=None) as batch_op:
        batch_op.drop_column('user_section')
        batch_op.drop_column('user_email')

    # ### end Alembic commands ###
