"""empty message

Revision ID: 54622122b290
Revises: 99767522c16b
Create Date: 2025-02-22 23:02:21.491096

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '54622122b290'
down_revision = '99767522c16b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_api', schema=None) as batch_op:
        batch_op.drop_column('ecreds_templates')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_api', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ecreds_templates', mysql.VARCHAR(length=999), nullable=True))

    # ### end Alembic commands ###
