"""empty message

Revision ID: 5ca9f1e6b9e6
Revises: d4f7b820de08
Create Date: 2025-03-19 11:11:03.613132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ca9f1e6b9e6'
down_revision = 'd4f7b820de08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('itexmo_api', schema=None) as batch_op:
        batch_op.add_column(sa.Column('credits_remaining', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('credits_consumed', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('itexmo_api', schema=None) as batch_op:
        batch_op.drop_column('credits_consumed')
        batch_op.drop_column('credits_remaining')

    # ### end Alembic commands ###
