"""empty message

Revision ID: 64683d12f53c
Revises: 
Create Date: 2025-02-23 21:33:44.324346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64683d12f53c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userv1', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('created_on', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('updated_by', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('updated_on', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userv1', schema=None) as batch_op:
        batch_op.drop_column('updated_on')
        batch_op.drop_column('updated_by')
        batch_op.drop_column('created_on')
        batch_op.drop_column('created_by')

    # ### end Alembic commands ###
