"""empty message

Revision ID: 745b1aa4daee
Revises: 4ff49caf100d
Create Date: 2025-04-08 11:30:47.041160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '745b1aa4daee'
down_revision = '4ff49caf100d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userv1', schema=None) as batch_op:
        batch_op.add_column(sa.Column('login_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('login_error_counter', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userv1', schema=None) as batch_op:
        batch_op.drop_column('login_error_counter')
        batch_op.drop_column('login_status')

    # ### end Alembic commands ###
