"""empty message

Revision ID: 865669c74283
Revises: fe2183fa93c0
Create Date: 2025-02-17 15:37:20.161679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '865669c74283'
down_revision = 'fe2183fa93c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hrpears_api', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hrpears_name', sa.String(length=200), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hrpears_api', schema=None) as batch_op:
        batch_op.drop_column('hrpears_name')

    # ### end Alembic commands ###
