"""empty message

Revision ID: 8a08b3ecc011
Revises: 18224a532314
Create Date: 2025-02-17 10:54:56.231475

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8a08b3ecc011'
down_revision = '18224a532314'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emails',
    sa.Column('ecreds_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ecreds_email', sa.String(length=100), nullable=False),
    sa.Column('ecreds_sender', sa.String(length=100), nullable=False),
    sa.Column('ecreds_password', sa.String(length=100), nullable=False),
    sa.Column('ecreds_templates', sa.String(length=999), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_on', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('updated_on', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('ecreds_id'),
    sa.UniqueConstraint('ecreds_id')
    )
    with op.batch_alter_table('e_creds', schema=None) as batch_op:
        batch_op.drop_index('ecreds_id')

    op.drop_table('e_creds')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('e_creds',
    sa.Column('ecreds_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('ecreds_email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('ecreds_sender', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('ecreds_password', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('ecreds_templates', mysql.VARCHAR(length=999), nullable=True),
    sa.Column('created_by', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('created_on', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('updated_by', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('updated_on', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('ecreds_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('e_creds', schema=None) as batch_op:
        batch_op.create_index('ecreds_id', ['ecreds_id'], unique=True)

    op.drop_table('emails')
    # ### end Alembic commands ###
