"""empty message

Revision ID: 8ae99ec6c453
Revises: 1f23504b1e4e
Create Date: 2025-02-11 14:06:31.962040

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8ae99ec6c453'
down_revision = '1f23504b1e4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userv1', schema=None) as batch_op:
        batch_op.drop_index('password')
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userv1', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', mysql.VARCHAR(length=50), nullable=False))
        batch_op.create_index('password', ['password'], unique=True)

    # ### end Alembic commands ###
