"""empty message

Revision ID: 8b71f3d002c4
Revises: de022288893c
Create Date: 2025-02-13 12:01:28.286921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b71f3d002c4'
down_revision = 'de022288893c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('itexmo',
    sa.Column('itexmo_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('itexmo_url', sa.String(length=200), nullable=False),
    sa.Column('itexmo_email', sa.String(length=200), nullable=False),
    sa.Column('itexmo_password', sa.String(length=200), nullable=False),
    sa.Column('itexmo_apicode', sa.String(length=200), nullable=False),
    sa.Column('itexmo_contenttype', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_on', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('updated_on', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('itexmo_id'),
    sa.UniqueConstraint('itexmo_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('itexmo')
    # ### end Alembic commands ###
