"""empty message

Revision ID: 8f766d5149d5
Revises: 4492e0fb8958
Create Date: 2025-02-25 21:10:15.288092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f766d5149d5'
down_revision = '4492e0fb8958'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('msg_log',
    sa.Column('msg_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('msg_tracker', sa.String(length=50), nullable=False),
    sa.Column('msg_type', sa.String(length=50), nullable=False),
    sa.Column('msg_sender', sa.String(length=50), nullable=False),
    sa.Column('msg_recipient', sa.Text(), nullable=True),
    sa.Column('msg_content', sa.Text(), nullable=True),
    sa.Column('msg_status', sa.String(length=50), nullable=True),
    sa.Column('sent_on', sa.String(length=100), nullable=True),
    sa.Column('msg_sent', sa.Text(), nullable=True),
    sa.Column('msg_unsent', sa.Text(), nullable=True),
    sa.Column('credit_used', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('msg_id'),
    sa.UniqueConstraint('msg_tracker')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('msg_log')
    # ### end Alembic commands ###
