"""empty message

Revision ID: 9392f08d1d3c
Revises: bce2bb687230
Create Date: 2025-02-17 13:08:06.949597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9392f08d1d3c'
down_revision = 'bce2bb687230'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userv1', schema=None) as batch_op:
        batch_op.add_column(sa.Column('msg_sent', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('credit_used', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userv1', schema=None) as batch_op:
        batch_op.drop_column('credit_used')
        batch_op.drop_column('msg_sent')

    # ### end Alembic commands ###
