"""empty message

Revision ID: 99767522c16b
Revises: dd087df4a1bf
Create Date: 2025-02-17 23:44:52.190194

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '99767522c16b'
down_revision = 'dd087df4a1bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('theme', schema=None) as batch_op:
        batch_op.add_column(sa.Column('theme_bg', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('theme_font', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('theme_icon', sa.String(length=100), nullable=True))
        batch_op.alter_column('theme_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('theme', schema=None) as batch_op:
        batch_op.alter_column('theme_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('theme_icon')
        batch_op.drop_column('theme_font')
        batch_op.drop_column('theme_bg')

    # ### end Alembic commands ###
