"""empty message

Revision ID: 9b9f900c0790
Revises: 6de0cae5e5d1
Create Date: 2025-02-24 09:21:07.645718

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9b9f900c0790'
down_revision = '6de0cae5e5d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sys_setting', schema=None) as batch_op:
        batch_op.alter_column('sys_app_user',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('sys_app_email',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('sys_app_phone',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('sys_app_user_text',
               existing_type=mysql.VARCHAR(length=900),
               nullable=True)
        batch_op.alter_column('sys_app_role_text',
               existing_type=mysql.VARCHAR(length=900),
               nullable=True)
        batch_op.alter_column('sys_app_division_text',
               existing_type=mysql.VARCHAR(length=900),
               nullable=True)
        batch_op.alter_column('sys_app_logs_text',
               existing_type=mysql.VARCHAR(length=900),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sys_setting', schema=None) as batch_op:
        batch_op.alter_column('sys_app_logs_text',
               existing_type=mysql.VARCHAR(length=900),
               nullable=False)
        batch_op.alter_column('sys_app_division_text',
               existing_type=mysql.VARCHAR(length=900),
               nullable=False)
        batch_op.alter_column('sys_app_role_text',
               existing_type=mysql.VARCHAR(length=900),
               nullable=False)
        batch_op.alter_column('sys_app_user_text',
               existing_type=mysql.VARCHAR(length=900),
               nullable=False)
        batch_op.alter_column('sys_app_phone',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('sys_app_email',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('sys_app_user',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###
