"""empty message

Revision ID: a0cf3cd31010
Revises: 9392f08d1d3c
Create Date: 2025-02-17 13:30:38.806765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0cf3cd31010'
down_revision = '9392f08d1d3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_api', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['ecreds_email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_api', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
