"""empty message

Revision ID: bce2bb687230
Revises: 428e834f0fd4
Create Date: 2025-02-17 11:50:46.610106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bce2bb687230'
down_revision = '428e834f0fd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userv1', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cur_login', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('last_login', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('last_logout', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userv1', schema=None) as batch_op:
        batch_op.drop_column('last_logout')
        batch_op.drop_column('last_login')
        batch_op.drop_column('cur_login')

    # ### end Alembic commands ###
