"""empty message

Revision ID: c77263bf43e4
Revises: e01e11be5f49
Create Date: 2025-02-13 15:46:21.942828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c77263bf43e4'
down_revision = 'e01e11be5f49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('login_api', schema=None) as batch_op:
        batch_op.add_column(sa.Column('login_api_name', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('login_api', schema=None) as batch_op:
        batch_op.drop_column('login_api_name')

    # ### end Alembic commands ###
