"""empty message

Revision ID: d4f7b820de08
Revises: e9bce9689be0
Create Date: 2025-03-05 11:26:29.375921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4f7b820de08'
down_revision = 'e9bce9689be0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('msg_templates',
    sa.Column('msg_temp_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('msg_temp_name', sa.String(length=100), nullable=False),
    sa.Column('msg_temp_description', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_on', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('updated_on', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('msg_temp_id'),
    sa.UniqueConstraint('msg_temp_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('msg_templates')
    # ### end Alembic commands ###
