"""empty message

Revision ID: d592d4ce77db
Revises: 5ca9f1e6b9e6
Create Date: 2025-03-21 08:18:52.652855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd592d4ce77db'
down_revision = '5ca9f1e6b9e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userv1', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userv1', schema=None) as batch_op:
        batch_op.drop_column('user_notes')

    # ### end Alembic commands ###
