"""empty message

Revision ID: dd087df4a1bf
Revises: 865669c74283
Create Date: 2025-02-17 16:12:58.345042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd087df4a1bf'
down_revision = '865669c74283'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sys_setting',
    sa.Column('sys_setting_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sys_app_name', sa.String(length=200), nullable=False),
    sa.Column('sys_app_user', sa.String(length=100), nullable=False),
    sa.Column('sys_app_email', sa.String(length=100), nullable=False),
    sa.Column('sys_app_phone', sa.String(length=100), nullable=False),
    sa.Column('msg_api_id', sa.Integer(), nullable=False),
    sa.Column('email_api_id', sa.Integer(), nullable=False),
    sa.Column('hris_api_id', sa.Integer(), nullable=False),
    sa.Column('login_api_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_on', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('updated_on', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['email_api_id'], ['email_api.ecreds_id'], ),
    sa.ForeignKeyConstraint(['hris_api_id'], ['hrpears_api.hrpears_id'], ),
    sa.ForeignKeyConstraint(['login_api_id'], ['login_api.login_api_id'], ),
    sa.ForeignKeyConstraint(['msg_api_id'], ['itexmo_api.itexmo_id'], ),
    sa.PrimaryKeyConstraint('sys_setting_id'),
    sa.UniqueConstraint('sys_setting_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sys_setting')
    # ### end Alembic commands ###
