"""empty message

Revision ID: df1160476efc
Revises: 64683d12f53c
Create Date: 2025-02-24 08:45:20.902997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df1160476efc'
down_revision = '64683d12f53c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sys_setting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sys_app_user_text', sa.String(length=900), nullable=False))
        batch_op.add_column(sa.Column('sys_app_role_text', sa.String(length=900), nullable=False))
        batch_op.add_column(sa.Column('sys_app_division_text', sa.String(length=900), nullable=False))
        batch_op.add_column(sa.Column('sys_app_logs_text', sa.String(length=900), nullable=False))
        batch_op.create_unique_constraint(None, ['sys_app_name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sys_setting', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('sys_app_logs_text')
        batch_op.drop_column('sys_app_division_text')
        batch_op.drop_column('sys_app_role_text')
        batch_op.drop_column('sys_app_user_text')

    # ### end Alembic commands ###
