"""empty message

Revision ID: e01e11be5f49
Revises: 8b71f3d002c4
Create Date: 2025-02-13 12:58:40.659974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e01e11be5f49'
down_revision = '8b71f3d002c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('itexmo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('itexmo_name', sa.String(length=200), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('itexmo', schema=None) as batch_op:
        batch_op.drop_column('itexmo_name')

    # ### end Alembic commands ###
