"""empty message

Revision ID: e0cfb6ce294f
Revises: b49b1a6ee8ad
Create Date: 2026-02-10 10:34:02.542156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0cfb6ce294f'
down_revision = 'b49b1a6ee8ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sys_setting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sys_app_aics_supplier_url', sa.String(length=900), nullable=True))
        batch_op.add_column(sa.Column('sys_app_aics_supplier_token', sa.String(length=900), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sys_setting', schema=None) as batch_op:
        batch_op.drop_column('sys_app_aics_supplier_token')
        batch_op.drop_column('sys_app_aics_supplier_url')

    # ### end Alembic commands ###
