"""empty message

Revision ID: e57ec5521145
Revises: fa7dae8520e8
Create Date: 2025-02-17 08:49:25.262536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e57ec5521145'
down_revision = 'fa7dae8520e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('e_creds',
    sa.Column('ecreds_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ecreds_email', sa.String(length=100), nullable=False),
    sa.Column('ecreds_sender', sa.String(length=100), nullable=False),
    sa.Column('ecreds_password', sa.String(length=100), nullable=False),
    sa.Column('ecreds_templates', sa.String(length=999), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_on', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('updated_on', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('ecreds_id'),
    sa.UniqueConstraint('ecreds_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('e_creds')
    # ### end Alembic commands ###
