"""empty message

Revision ID: e9bce9689be0
Revises: 8f766d5149d5
Create Date: 2025-02-26 11:19:34.800108

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e9bce9689be0'
down_revision = '8f766d5149d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('msg_log', schema=None) as batch_op:
        batch_op.alter_column('credit_used',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('msg_log', schema=None) as batch_op:
        batch_op.alter_column('credit_used',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###
