"""empty message

Revision ID: ea8427440f4b
Revises: e69dcd72f0fc
Create Date: 2025-02-10 17:49:23.569520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea8427440f4b'
down_revision = 'e69dcd72f0fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('divisions',
    sa.Column('division_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('division_name', sa.String(length=100), nullable=False),
    sa.Column('division_description', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_on', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('updated_on', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('division_id'),
    sa.UniqueConstraint('division_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('divisions')
    # ### end Alembic commands ###
