"""empty message

Revision ID: ef4b365c0868
Revises: 4aeca864b60e
Create Date: 2025-04-25 11:28:20.210461

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ef4b365c0868'
down_revision = '4aeca864b60e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('msg_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('msg_division', sa.String(length=50), nullable=False))
        batch_op.alter_column('msg_sender',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=200),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('msg_log', schema=None) as batch_op:
        batch_op.alter_column('msg_sender',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('msg_division')

    # ### end Alembic commands ###
