"""empty message

Revision ID: fa7dae8520e8
Revises: 1f5a18a2a599
Create Date: 2025-02-17 00:09:21.875749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa7dae8520e8'
down_revision = '1f5a18a2a599'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('login_api', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['login_api_name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('login_api', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
