"""empty message

Revision ID: fe2183fa93c0
Revises: a0cf3cd31010
Create Date: 2025-02-17 13:32:23.483235

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fe2183fa93c0'
down_revision = 'a0cf3cd31010'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_api', schema=None) as batch_op:
        batch_op.alter_column('ecreds_sender',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_api', schema=None) as batch_op:
        batch_op.alter_column('ecreds_sender',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###
